# Generated by Django 5.2.4 on 2025-08-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
