# Generated by Django 5.2.4 on 2025-11-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_timetable_options_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preference',
            options={'ordering': ('-score',)},
        ),
    ]
