# Generated by Django 5.2.4 on 2025-11-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_preference_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
