# Generated by Django 5.2.4 on 2025-11-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_preference_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('classroom', 'time_slot', 'timetable'), ('division', 'time_slot', 'timetable'), ('teacher', 'time_slot', 'timetable')},
        ),
    ]
